const contacts = window.CRM_CONTACTS || [];
const totals = window.CRM_TOTALS || {};
const rowsEl = document.getElementById('rows');
const navEl = document.getElementById('nav');
const detailEl = document.getElementById('detailPanel');
const selectedEl = document.getElementById('selectedList');
const searchEl = document.getElementById('search');
const visibleEl = document.getElementById('visibleCount');
const resultEl = document.getElementById('resultText');
let activeDomain = 'All';
let activeId = contacts[0]?.name || '';
let selected = JSON.parse(localStorage.getItem('zain-crm-selected') || '[]');
const domains = ['All','Work','Projects','Growth','Systems','Personal','Health'];
function logo(contact){const d=(contact.company||contact.name||'').toLowerCase();return `<span class="logo"><img alt="" src="https://www.google.com/s2/favicons?domain=${encodeURIComponent(d)}&sz=128"></span>`}
function row(contact){const hay=[contact.name,contact.company,contact.email,contact.domain,contact.type,contact.snippet].join(' ').toLowerCase();return `<tr draggable="true" data-id="${contact.name}" data-domain="${contact.domain}" data-search="${hay}"><td><span class="check">v</span></td><td><div class="person">${logo(contact)}<div><div class="name">${contact.name}</div><div class="email">${contact.email}</div></div></div></td><td>${contact.company}</td><td>-</td><td>${contact.lastContact}</td><td class="value">${contact.value}</td></tr>`}
function renderNav(){const counts={All:totals.contacts||contacts.length,Work:totals.work||0,Projects:totals.projects||0,Growth:totals.growth||0,Systems:totals.systems||0,Personal:totals.personal||0,Health:totals.health||0};navEl.innerHTML=domains.filter(d=>d==='All'||counts[d]).map(d=>`<button class="${d===activeDomain?'active':''}" data-domain="${d}"><span>${d[0]}</span><span>${d==='All'?'Dashboard':d}</span><span>${counts[d].toLocaleString()}</span></button>`).join('')}
function renderRows(){rowsEl.innerHTML=contacts.map(row).join('');rowsEl.querySelectorAll('tr').forEach(tr=>{tr.addEventListener('click',()=>{activeId=tr.dataset.id;addSelected(activeId);renderAll()});tr.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',tr.dataset.id))})}
function filterRows(){const q=searchEl.value.toLowerCase().trim();let count=0;rowsEl.querySelectorAll('tr').forEach(tr=>{const ok=(activeDomain==='All'||tr.dataset.domain===activeDomain)&&(!q||tr.dataset.search.includes(q));tr.classList.toggle('hidden',!ok);tr.classList.toggle('active',tr.dataset.id===activeId);if(ok)count++});visibleEl.textContent=count.toLocaleString();resultEl.textContent=`Showing ${count.toLocaleString()} of ${(totals.contacts||contacts.length).toLocaleString()} results`}
function activeContact(){return contacts.find(c=>c.name===activeId)||contacts[0]}
function renderDetail(){const c=activeContact(); if(!c)return;detailEl.innerHTML=`<section class="profile">${logo(c)}<h2>${c.name}</h2><p>${c.type} at ${c.company}</p><div class="quick-actions"><button>P</button><button>@</button><button>N</button><button>...</button></div></section><div class="tabs"><button class="tab active" data-tab="overview">Overview</button><button class="tab" data-tab="activity">Activity</button><button class="tab" data-tab="notes">Notes</button></div><section class="panel active" data-panel="overview"><h3 class="section-title">Contact Details</h3><div class="detail-list"><div class="line"><span class="mini">@</span><span>${c.email}<small class="tiny">${c.type}</small></span></div><div class="line"><span class="mini">P</span><span>-<small class="tiny">Phone</small></span></div><div class="line"><span class="mini">D</span><span>${c.company}<small class="tiny">${c.domain}</small></span></div></div><h3 class="section-title">Properties</h3><div class="props"><div class="prop"><div class="prop-label">Source</div><div class="prop-value">${c.source}</div></div><div class="prop"><div class="prop-label">Priority</div><div class="prop-value">${c.priority}</div></div><div class="prop"><div class="prop-label">Rows</div><div class="prop-value">${c.count} source rows</div></div><div class="prop"><div class="prop-label">Value</div><div class="prop-value">${c.value}</div></div></div></section><section class="panel" data-panel="activity"><h3 class="section-title">Recent Activity</h3><div class="activity-item"><strong>Email thread 1</strong>${c.snippet}<small class="tiny">${c.lastContact}</small></div></section><section class="panel" data-panel="notes"><h3 class="section-title">Notes</h3><textarea placeholder="Write notes for ${c.name}"></textarea></section>`;detailEl.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{detailEl.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));detailEl.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===b.dataset.tab))}))}
function addSelected(id){if(!selected.includes(id)){selected.push(id);saveSelected()}}
function saveSelected(){localStorage.setItem('zain-crm-selected',JSON.stringify(selected))}
function renderSelected(){selectedEl.innerHTML=selected.map(id=>`<div class="pill" data-id="${id}"><span>${id}</span><button class="remove">x</button></div>`).join('');selectedEl.querySelectorAll('.pill').forEach(p=>p.addEventListener('click',e=>{if(e.target.closest('.remove')){selected=selected.filter(id=>id!==p.dataset.id);saveSelected();renderSelected();return}activeId=p.dataset.id;renderAll()}))}
function renderAll(){renderNav();filterRows();renderDetail();renderSelected()}
navEl.addEventListener('click',e=>{const b=e.target.closest('button[data-domain]');if(!b)return;activeDomain=b.dataset.domain;renderAll()});searchEl.addEventListener('input',filterRows);document.getElementById('clearSelected').addEventListener('click',()=>{selected=[];saveSelected();renderSelected()});renderNav();renderRows();renderAll();
