const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={person:'<circle cx="12" cy="12" r="10"/><circle cx="12" cy="8" r="3" fill="currentColor"/><path d="M6 19v-2a4 4 0 0 1 4-4h4a4 4 0 0 1 4 4v2" fill="currentColor"/>',company:'<path d="M3 21V7l6 3V3l6 3v6l6-3v12H3M9 10v11M15 12v9M11 7l2 1M11 10l2 1M5 11l2 1M5 14l2 1M5 17l2 1M17 14l2-1M17 17l2-1"/>',phone:'<path d="M22 16.9v3a2 2 0 0 1-2.2 2 19.8 19.8 0 0 1-8.6-3.1 19.5 19.5 0 0 1-6-6 19.8 19.8 0 0 1-3-8.7A2 2 0 0 1 4.1 2h3a2 2 0 0 1 2 1.7c.1 1 .4 2 .7 2.8a2 2 0 0 1-.5 2.1L8.1 9.9a16 16 0 0 0 6 6l1.3-1.2a2 2 0 0 1 2.1-.5c.9.3 1.8.6 2.8.7A2 2 0 0 1 22 16.9z"/>',email:'<circle cx="12" cy="12" r="4"/><path d="M16 8v5a3 3 0 0 0 6 0v-1a10 10 0 1 0-4 8"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M3 10h18M7 2v6M17 2v6M7 14h1m3 0h1m3 0h1M7 17h1m3 0h1m3 0h1"/>',tag:'<path d="M5 8l4-6h6l4 6v14H5z"/><circle cx="12" cy="6" r="1"/>',logo:'<circle cx="12" cy="12" r="9"/><path d="M6 14V9m0 5h3m2-4v4h3v-4zm5 0v4h2"/>',history:'<path d="M3 12h4l3-8 4 16 3-8h4"/>',network:'<circle cx="5" cy="5" r="2"/><circle cx="19" cy="5" r="2"/><circle cx="12" cy="19" r="2"/><path d="M5 7v4h14V7M12 11v6"/>',layers:'<path d="M3 7l9-5 9 5-9 5zM3 12l9 5 9-5M3 17l9 5 9-5"/>',search:'<circle cx="10" cy="10" r="7"/><path d="M15 15l6 6"/>',cards:'<rect x="5" y="3" width="15" height="18" rx="2"/><path d="M2 7v12M9 8h7M9 12h7M9 16h4"/>',notes:'<path d="M21 11a9 9 0 0 1-9 9H3l2-5a9 9 0 1 1 16-4z"/>'};
const icon=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[n]||paths.person}</svg>`;
const groupBy=(items,key)=>items.reduce((groups,item)=>{const k=key(item);(groups[k]??=[]).push(item);return groups},Object.create(null));
const initials=n=>String(n).split(/\s+/).map(s=>s[0]).slice(0,2).join('').toUpperCase();
let contacts=[],companies=[],view='people',layout='cards',page=0,search='',label='',sort='name'; const size=24;
const names={people:'Contacts',companies:'Companies',history:'Touchpoints',network:'Network'};
$('#brand-icon').innerHTML=icon('layers');$('#search-icon').innerHTML=icon('search');$('#nav').innerHTML=[['people','person','People'],['companies','company','Companies'],['history','history','History'],['network','network','Network']].map(([v,i,t])=>`<button data-go="${v}" class="${v===view?'active':''}" aria-label="${t}">${icon(i)}<span>${t}</span></button>`).join('');
function filtered(){const source=view==='companies'?companies:contacts;return source.filter(c=>(!search||[c.name,c.company,c.email,c.domain].join(' ').toLowerCase().includes(search))&&(!label||(c.labels||[c.label]).includes(label))).sort((a,b)=>sort==='recent'?b.date.localeCompare(a.date):a.name.localeCompare(b.name));}
function field(i,title,value){return `<div class="field"><span class="icon-tile">${icon(i)}</span><div class="field-body"><b>${title}</b><span class="value">${value||'Not added'}</span></div></div>`;}
function card(c,full=false){return `<div class="identity-head"><span class="identity-symbol">${c.logo?`<img class="brand-logo" src="${esc(c.logo)}" alt="${esc(c.company)} logo">`:icon(c.members?'company':'person')}</span><div><h2 ${full?'id="profile-name"':''}>${esc(c.name)}</h2>${c.members?'':`<p>${esc(c.company)}</p>`}</div></div>${field('phone','Phone number',esc(c.phone))}${field('email','Email',esc(c.email))}${field('calendar','Date contacted',esc(c.date))}${field('tag','Label',c.label?`<span class="tag">${esc(c.label)}</span>`:'Unlabelled')}${field('logo','Logo',c.logo?`<img class="field-logo" src="${esc(c.logo)}" alt="${esc(c.company)} logo">`:'Not added')}`;}
function render(){document.querySelectorAll('[data-go]').forEach(b=>{if(b.closest('nav')){b.classList.toggle('active',b.dataset.go===view);b.setAttribute('aria-current',b.dataset.go===view?'page':'false')}});$('#title').textContent=names[view];document.querySelectorAll('[data-layout]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.layout===layout)));$('#view-options').hidden=['network','history'].includes(view);let list=filtered(),slice=list.slice(page*size,(page+1)*size);$('#result-count').textContent=`${list.length.toLocaleString()} ${view==='companies'?'companies':'contacts'}`;
 if(view==='network'){renderNetwork(list);$('#pagination').innerHTML='';return;}if(view==='history'){renderHistory(list);$('#pagination').innerHTML='';return;}
 if(!slice.length)$('#content').innerHTML='<p class="empty">No contacts match your search.</p>';
 else if(layout==='cards')$('#content').innerHTML=`<div class="cards">${slice.map(c=>`<article class="identity-card">${card(c)}<div class="card-action"><button data-open="${esc(c.id)}">More info →</button></div></article>`).join('')}</div>`;
 else $('#content').innerHTML=`<div class="table-wrap"><table><thead><tr>${['Person','Company','Phone number','Email','Last contacted','Label',''].map(t=>`<th scope="col">${t}</th>`).join('')}</tr></thead><tbody>${slice.map(c=>`<tr><td><button class="person-link" data-open="${esc(c.id)}"><span class="mini-avatar">${esc(initials(c.name))}</span>${esc(c.name)}</button></td><td>${esc(c.company)}</td><td class="muted">${esc(c.phone||'—')}</td><td class="muted">${esc(c.email)}</td><td>${esc(c.date)}</td><td>${c.label?`<span class="tag">${esc(c.label)}</span>`:'—'}</td><td><button class="more" data-open="${esc(c.id)}">More info</button></td></tr>`).join('')}</tbody></table></div>`;
 const pages=Math.ceil(list.length/size);$('#pagination').innerHTML=pages>1?`<button data-page="-1" ${page===0?'disabled':''}>Previous</button><span>${page+1} / ${pages}</span><button data-page="1" ${page+1>=pages?'disabled':''}>Next</button>`:'';
}
function message(m){return `<details class="message"><summary>${esc(m.subject||'(No subject)')}<time>${esc(m.date)}</time></summary><div class="message-body"><small>Saved spreadsheet snippet</small><p>${esc(m.snippet)}</p><small>${esc(m.status||'')} · ${esc(m.context||'')} · ${m.copies||1} source row(s)</small></div></details>`;}
async function historyFor(c){if(c.members){return (await Promise.all(c.members.map(historyFor))).flat().sort((a,b)=>b.date.localeCompare(a.date));}const r=await fetch(`history/${c.id}.json`);if(!r.ok)throw Error('History unavailable');return r.json();}
let openToken=0;
function renderNetwork(list){const groups=groupBy(list,c=>c.domain);$('#content').innerHTML=`<div class="network"><h2>Network</h2><p class="muted">People and companies, connected by domain.</p>${Object.entries(groups).sort(([a],[b])=>a.localeCompare(b)).map(([d,cs])=>`<details><summary>${esc(d)} <small>${cs.length} ${cs.length===1?'contact':'contacts'} · ${cs.reduce((n,c)=>n+c.count,0)} messages</small></summary>${cs.map(c=>`<button data-open="${c.id}">${icon('person')} &nbsp; ${esc(c.name)}<br><span class="muted">${esc(c.email)}</span></button>`).join('')}</details>`).join('')}</div>`;}
function renderHistory(list){$('#content').innerHTML=`<div class="network">${list.slice(0,100).map(c=>`<details><summary>${esc(c.name)} <small>${c.count} messages · last ${esc(c.date)}</small></summary><button data-open="${c.id}">Open contact history →</button></details>`).join('')}${list.length>100?'<p class="muted">Search to narrow the contact history list.</p>':''}</div>`;}
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.go){view=b.dataset.go;page=0;render();}if(b.dataset.layout){layout=b.dataset.layout;page=0;render();}if(b.dataset.open)openProfile(b.dataset.open);if(b.dataset.page){page+=Number(b.dataset.page);render();$('#content').scrollIntoView({block:'start'});}});
$('#search').addEventListener('input',e=>{search=e.target.value.toLowerCase().trim();page=0;render()});$('#labels').onchange=e=>{label=e.target.value;page=0;render()};$('#sort').onchange=e=>{sort=e.target.value;page=0;render()};$('.close').onclick=()=>$('#profile').close();$('#profile').addEventListener('click',e=>{if(e.target===$('#profile'))$('#profile').close()});
fetch('contacts.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{contacts=data;const groups=groupBy(data,c=>c.domain);companies=Object.entries(groups).map(([domain,members])=>({id:'company-'+domain,name:domain==='hyatt.com'?'Hyatt':domain,company:domain,domain,email:members.map(c=>c.email).join(', '),phone:'',date:members.reduce((d,c)=>c.date>d?c.date:d,''),label:'',members,count:members.reduce((n,c)=>n+c.count,0)}));companies.forEach(c=>{const m=c.members.find(x=>x.logo);if(m){c.logo=m.logo;c.name=m.company;c.company=m.company;c.blueprintPath=m.blueprintPath;}c.labels=[...new Set(c.members.flatMap(x=>x.labels||[]))];c.label=c.labels.join(', ');});$('#peopleCount').textContent=data.length.toLocaleString();$('#companyCount').textContent=companies.length.toLocaleString();$('#historyCount').textContent=data.reduce((n,c)=>n+c.count,0).toLocaleString();$('#labels').innerHTML='<option value="">All labels</option>'+[...new Set(data.flatMap(c=>c.labels||[c.label]).filter(Boolean))].sort().map(l=>`<option>${esc(l)}</option>`).join('');render();}).catch(()=>{$('#content').innerHTML='<p class="empty">Contacts could not load. Please reload the page to retry.</p>'});
if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'find_contacts',description:'Search the imported contacts and update the visible contact list.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(!input||typeof input.query!=='string')throw new Error('query must be a string');view='people';search=input.query.toLowerCase().trim();$('#search').value=input.query;page=0;render();return {count:filtered().length,contacts:filtered().slice(0,20).map(c=>({id:c.id,name:c.name,email:c.email}))};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}

fetch('data-summary.json').then(r=>r.json()).then(d=>{$('#coverage').textContent=d.sourceRows.toLocaleString()+' source rows · '+d.uniqueRecords.toLocaleString()+' distinct records · '+d.firstDate+' to '+d.lastDate;}).catch(()=>{});
renderNetwork=function(list){const tree={children:new Map(),contacts:[]};for(const c of list){let n=tree;for(const part of [...(c.blueprintPath||['Unlabelled']),c.domain]){if(!n.children.has(part))n.children.set(part,{children:new Map(),contacts:[]});n=n.children.get(part);}n.contacts.push(c);}function branch(n){return [...n.children].sort(([a],[b])=>a.localeCompare(b)).map(([name,child])=>`<details><summary>${esc(name)}</summary>${branch(child)}</details>`).join('')+n.contacts.map(c=>`<button data-open="${esc(c.id)}">${c.logo?`<img src="${esc(c.logo)}" alt="" style="width:28px;height:28px;object-fit:contain;vertical-align:middle;margin-right:8px">`:icon('person')} ${esc(c.name)}<br><span class="muted">${esc(c.email)}</span></button>`).join('');}$('#content').innerHTML='<div class="network">'+branch(tree)+'</div>';};
let selectedProfiles=[],drawerToken=0;
function drawerTab(name){document.querySelectorAll('[data-drawer-tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.drawerTab===name)));document.querySelectorAll('[data-drawer-panel]').forEach(p=>p.hidden=p.dataset.drawerPanel!==name);}
async function openProfile(id){const c=contacts.find(c=>c.id===id)||companies.find(c=>c.id===id);if(!c)return;const token=++drawerToken;if(!selectedProfiles.includes(id))selectedProfiles.push(id);const get=id=>contacts.find(c=>c.id===id)||companies.find(c=>c.id===id);const members=c.members||[c];const emails=members.map(p=>p.email);const prop=(label,value)=>`<div class="drawer-prop"><span>${label}</span><b>${esc(value)}</b></div>`;
$('#profile-content').innerHTML=`<div class="selected-box"><b>Selected contacts</b><p>Click a person or company to add it here.</p><div class="selected-pills">${selectedProfiles.map(id=>`<span><button data-open="${esc(id)}">${esc(get(id)?.name||id)}</button><button data-remove-profile="${esc(id)}" aria-label="Remove ${esc(get(id)?.name||id)}">×</button></span>`).join('')}</div></div><section class="drawer-identity"><div class="drawer-avatar">${c.logo?`<img src="${esc(c.logo)}" alt="${esc(c.company)} logo">`:icon(c.members?'company':'person')}</div><h2 id="profile-name">${esc(c.name)}</h2><p>${c.members?`${members.length} contacts`:esc(c.company)}</p><div class="drawer-actions">${c.phone?`<a href="tel:${esc(c.phone)}" aria-label="Call">${icon('phone')}</a>`:`<button disabled aria-label="No phone number">${icon('phone')}</button>`}<a href="mailto:${esc(emails.join(','))}" aria-label="Compose email">${icon('email')}</a><button data-switch-drawer="notes" aria-label="Show notes">${icon('notes')}</button></div></section><div class="drawer-tabs" role="tablist" aria-label="Contact details"><button role="tab" aria-selected="true" data-drawer-tab="overview">Overview</button><button role="tab" aria-selected="false" data-drawer-tab="activity">Activity</button><button role="tab" aria-selected="false" data-drawer-tab="notes">Notes</button></div><section class="drawer-section" role="tabpanel" data-drawer-panel="overview"><h3>Contact details</h3><div class="drawer-line">${icon('email')}<div>${emails.map(e=>`<span>${esc(e)}</span>`).join('')}<small>Email</small></div></div><div class="drawer-line">${icon('phone')}<div>${esc(c.phone||'Not added')}<small>Phone</small></div></div><div class="drawer-line">${icon('company')}<div>${esc(c.domain)}<small>${esc(c.blueprintPath?.join(' / ')||'Unlabelled')}</small></div></div><h3>Properties</h3><div class="drawer-props">${prop('Source','Spreadsheet')}${prop('Label',c.label||'Unlabelled')}${prop('Records',c.count.toLocaleString())}${prop('Last contacted',c.date)}</div>${c.members?`<h3>People</h3>${members.map(m=>`<button class="drawer-person" data-open="${esc(m.id)}">${esc(m.name)}<small>${esc(m.email)}</small></button>`).join('')}`:''}</section><section class="drawer-section" role="tabpanel" data-drawer-panel="activity" hidden><h3>Contact history</h3><div id="drawer-history">Loading history…</div></section><section class="drawer-section" role="tabpanel" data-drawer-panel="notes" hidden><h3>Notes & context</h3><div id="drawer-notes">Loading saved context…</div></section>`;
if(!$('#profile').open){if(innerWidth<=700)$('#profile').showModal();else $('#profile').show();}document.body.classList.add('drawer-open');
try{const history=await historyFor(c);if(token!==drawerToken)return;$('#drawer-history').innerHTML=Object.entries(groupBy(history,m=>m.date.slice(0,4))).sort(([a],[b])=>b.localeCompare(a)).map(([year,rows])=>`<details><summary>${year} · ${rows.length} records</summary>${Object.entries(groupBy(rows,m=>m.date.slice(0,7))).map(([month,rs])=>`<details><summary>${month}</summary>${rs.map(message).join('')}</details>`).join('')}</details>`).join('');const notes=[...new Set(history.map(m=>m.context).filter(s=>s&&s!=='No prior context'))];$('#drawer-notes').innerHTML=notes.length?notes.map(n=>`<p class="context-note">${esc(n)}</p>`).join(''):'<p class="muted">No notes in the imported spreadsheet.</p>';}catch{if(token===drawerToken){$('#drawer-history').textContent='History could not load. Reopen this contact to retry.';$('#drawer-notes').textContent='Context unavailable.';}}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.drawerTab)drawerTab(b.dataset.drawerTab);if(b.dataset.switchDrawer)drawerTab(b.dataset.switchDrawer);if(b.dataset.removeProfile){selectedProfiles=selectedProfiles.filter(id=>id!==b.dataset.removeProfile);b.closest('.selected-pills>span').remove();}});
$('#profile').addEventListener('close',()=>{document.body.classList.remove('drawer-open');drawerToken++;});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#profile').open)$('#profile').close();const b=e.target.closest('[data-drawer-tab]');if(b&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const tabs=[...document.querySelectorAll('[data-drawer-tab]')];const next=tabs[(tabs.indexOf(b)+(e.key==='ArrowRight'?1:2))%3];next.focus();drawerTab(next.dataset.drawerTab);}});

let blueprintRows=null,blueprintLinks={},blueprintRemoved={nodes:[],links:{}},blueprintFailed=false;
const blueprintExpanded=new Set();
const blueprintKey=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]/g,'');
renderNetwork=function(list){
 if(!blueprintRows){$('#content').innerHTML=`<p class="empty">${blueprintFailed?'Blueprint could not load. Reload to retry.':'Loading complete blueprint…'}</p>`;return;}
 const nodes=new Map([...blueprintRows,...blueprintRemoved.nodes].map(r=>[r.id,{...r,children:[],people:[]}]));const roots=[];
 for(const n of nodes.values()){if(n.parentId)nodes.get(n.parentId).children.push(n);else roots.push(n);}
 const matched=new Set();for(const c of list){const active=blueprintLinks.links?blueprintLinks.links.filter(r=>c.domain.toLowerCase()===r.domain.toLowerCase()).map(r=>r.sectionId):(blueprintLinks[c.id]||[]);for(const id of active){const n=nodes.get(id);if(n){n.people.push(c);matched.add(c.id);}}for(const id of blueprintRemoved.links[c.id]||[]){nodes.get(id)?.people.push(c);}}for(const n of nodes.values())n.children.sort((a,b)=>(a.order??999)-(b.order??999));roots.sort((a,b)=>(a.order??999)-(b.order??999));
 function accounts(people){return Object.values(groupBy(people,c=>c.company||c.domain)).map(cs=>{const c=cs[0];return `<details class="account-group"><summary>${c.logo?`<img src="${esc(c.logo)}" alt="">`:icon('company')}<span>${esc(c.company||c.domain)}<small>${cs.length} ${cs.length===1?'account':'accounts'}</small></span></summary><div>${cs.map(p=>`<button class="account-row" data-open="${esc(p.id)}">${p.logo?`<img src="${esc(p.logo)}" alt="">`:icon('person')}<span class="account-name">${esc(p.name)}</span><span class="email-badge" title="${esc(p.email)}">${esc(p.email)}</span><span aria-hidden="true">›</span></button>`).join('')}</div></details>`}).join('');}

 const q=search.toLowerCase();function branch(n,ancestorMatch=false){const selfMatch=ancestorMatch||!!q&&[n.name,n.description,n.hierarchyPath].join(' ').toLowerCase().replaceAll('_',' ').includes(q);const children=n.children.map(x=>branch(x,selfMatch)).join('');const people=accounts(n.people);if(!n.children.length&&n.people.length){if((q||label)&&!selfMatch&&!people)return '';const logo=n.logo;return `<details class="account-group blueprint-node blueprint-leaf" data-blueprint-id="${esc(n.id)}" ${blueprintExpanded.has(n.id)||q?'open':''}><summary>${logo?`<img src="${esc(logo)}" alt="">`:icon('company')}<span>${esc(n.name.replaceAll('_',' '))}<small>${n.people.length} ${n.people.length===1?'account':'accounts'}</small></span></summary><div>${n.description&&n.source?`<p class="blueprint-description">${esc(n.description)}</p>`:''}${n.people.map(p=>`<button class="account-row" data-open="${esc(p.id)}">${p.logo?`<img src="${esc(p.logo)}" alt="">`:icon('person')}<span class="account-name">${esc(p.name)}</span><span class="email-badge" title="${esc(p.email)}">${esc(p.email)}</span><span aria-hidden="true">›</span></button>`).join('')}</div></details>`;}if((q||label)&&!selfMatch&&!children&&!people)return '';return `<details class="blueprint-node" data-blueprint-id="${esc(n.id)}" ${blueprintExpanded.has(n.id)||q?'open':''}><summary><span>${esc(n.name.replaceAll('_',' '))}</span><small>${n.children.length?`${n.children.length} items`:n.people.length?`${n.people.length} contacts`:''}</small></summary><div class="blueprint-body">${n.description?`<p class="blueprint-description">${esc(n.description)}</p>`:''}${children}${people}${!children&&!people?'<p class="blueprint-empty">No linked contacts yet.</p>':''}</div></details>`;}
 const unmatched=list.filter(c=>!matched.has(c.id));$('#content').innerHTML=`<section class="blueprint"><header><h2>Network</h2><p>A map of people, places, projects, and systems connected to you.</p><div class="blueprint-controls"><span>${blueprintRows.length} blueprint entries</span><button data-blueprint-action="expand">Expand all</button><button data-blueprint-action="collapse">Collapse all</button></div></header><div class="blueprint-tree">${roots.map(n=>branch(n)).join('')||'<p class="blueprint-empty">No matching blueprint entries.</p>'}<details class="blueprint-node" data-blueprint-id="unmatched" ${blueprintExpanded.has('unmatched')?'open':''}><summary><span>Unassigned contacts</span><small>${unmatched.length}</small></summary><div class="blueprint-body">${unmatched.map(c=>`<button class="blueprint-contact" data-open="${esc(c.id)}">${icon('person')}<span>${esc(c.name)}<small>${esc(c.email)}</small></span></button>`).join('')||'<p class="blueprint-empty">All matching contacts are linked.</p>'}</div></details></div></section>`;
};
document.addEventListener('toggle',e=>{const id=e.target.dataset?.blueprintId;if(id){if(e.target.open)blueprintExpanded.add(id);else blueprintExpanded.delete(id);}},true);
document.addEventListener('click',e=>{const action=e.target.closest('[data-blueprint-action]')?.dataset.blueprintAction;if(action)document.querySelectorAll('[data-blueprint-id]').forEach(d=>{d.open=action==='expand';if(d.open)blueprintExpanded.add(d.dataset.blueprintId);else blueprintExpanded.delete(d.dataset.blueprintId);});});
Promise.all(['blueprint.json','blueprint-links.json','blueprint-removed.json'].map(url=>fetch(url).then(r=>{if(!r.ok)throw Error();return r.json()}))).then(([rows,links,removed])=>{blueprintRows=rows;blueprintLinks=links;blueprintRemoved=removed;if(view==='network')render();}).catch(()=>{blueprintFailed=true;if(view==='network')render();});
