/* Parent owns storage because the Inbox iframe intentionally has an opaque origin. */
(()=>{
 const openDB=()=>new Promise((resolve,reject)=>{const r=indexedDB.open('organize-me-apple',1);r.onupgradeneeded=()=>r.result.createObjectStore('snapshots');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
 async function access(mode,data){const db=await openDB();try{return await new Promise((resolve,reject)=>{const tx=db.transaction('snapshots',mode),s=tx.objectStore('snapshots');const r=mode==='readonly'?s.get('current'):s.put(data,'current');tx.oncomplete=()=>resolve(r.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}finally{db.close();}}
 function mountImport(){const frame=document.querySelector('.inbox-frame');if(!frame||document.querySelector('#apple-parent-import'))return;const bar=document.createElement('div');bar.id='apple-parent-import';bar.style.cssText='display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin-bottom:16px;font-size:12px';bar.innerHTML='<label style="position:relative;display:inline-flex;align-items:center;min-height:44px;padding:10px 14px;border:1px solid #ddd;border-radius:10px;color:#7546ff;cursor:pointer">Import Apple history<input type="file" accept=".json,application/json" aria-label="Import Apple Messages and call history" style="position:absolute;inset:0;opacity:0;width:100%;cursor:pointer"></label><span role="status">Apple imports stay in this browser.</span>';frame.before(bar);bar.querySelector('input').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;const status=bar.querySelector('[role="status"]');try{const data=JSON.parse(await file.text());if(data?.format!=='organize-me-apple-v1'||!Array.isArray(data.records))throw Error('Choose an Apple history export JSON.');await access('readwrite',data);frame.contentWindow.postMessage({type:'crm-apple-data',data},'*');status.textContent=data.records.length.toLocaleString()+' Apple records saved in this browser.';}catch(error){status.textContent=error.message;}finally{e.target.value='';}});}
 new MutationObserver(mountImport).observe(document.querySelector('#content'),{childList:true});mountImport();
 window.addEventListener('message' ,async event=>{const frame=document.querySelector('.inbox-frame');if(!frame||event.source!==frame.contentWindow||event.origin!=='null')return;const target=frame.contentWindow;
 if(event.data?.type==='crm-apple-ready'){try{const data=await access('readonly');if(data)target.postMessage({type:'crm-apple-data',data},'*');}catch{}}
 if(event.data?.type==='crm-apple-save'){let ok=false;try{const data=event.data.data;if(data?.format!=='organize-me-apple-v1'||!Array.isArray(data.records))throw Error('Invalid export');await access('readwrite',data);ok=true;}catch{}target.postMessage({type:'crm-apple-saved',ok},'*');}
 });
})();
