/* Apple imports stay in this browser. No upload, sending, or dialing. */
let appleSource=null,inboxPage=0;
const inboxPageSize=75;
const gmailOnly=messages.slice();
function availableChannel(channel){return channel==='All Comms'||channel==='Gmail'||Boolean(appleSource?.sources?.[channel]);}
function applyAppleImport(data){
 if(data?.format!=='organize-me-apple-v1'||!Array.isArray(data.records))throw Error('Choose an organize-me Apple export JSON file.');
 const seen=new Set();const imported=[];
 for(const r of data.records){
  if(!['Apple Messages','Apple Phone'].includes(r.channel)||typeof r.id!=='string'||!r.id.startsWith('apple-')||!Number.isFinite(Date.parse(r.date))||seen.has(r.id))continue;
  seen.add(r.id);imported.push({id:r.id,channel:r.channel,sender:String(r.sender||r.address||'Unknown contact'),email:String(r.address||''),date:r.date,dateKey:isoLocal(new Date(r.date)),subject:String(r.subject||''),preview:String(r.preview||''),status:String(r.status||''),direction:r.direction,unread:r.unread===true,hasAttachment:r.hasAttachment===true,service:String(r.service||''),participants:Array.isArray(r.participants)?r.participants.map(String):[],threadId:r.threadId,textState:r.textState});
 }
 appleSource={...data,records:undefined};messages.length=0;for(const r of [...gmailOnly,...imported].sort((a,b)=>Date.parse(b.date)-Date.parse(a.date)))messages.push(r);
 inboxPage=0;selectedMessage=null;inboxAnchor=new Date(messages[0]?.date||Date.now());
 document.querySelector('.comms-note').textContent=`${gmailOnly.length} Gmail messages · ${imported.filter(m=>m.channel==='Apple Messages').length.toLocaleString()} Apple message records · ${imported.filter(m=>m.channel==='Apple Phone').length.toLocaleString()} calls · Apple export ${new Date(data.exportedAt).toLocaleString()} · Snapshots, not continuous sync`;
 for(const channel of ['Apple Messages','Apple Phone']){const el=document.querySelector(`[data-channel="${channel}"]`);el?.querySelector('.notification-badge')?.remove();const count=imported.filter(r=>r.channel===channel&&r.unread).length;if(count){actualBadge(el,count);el.querySelector('.notification-badge').title=`${count} unread in imported Apple messages`;el.querySelector('.notification-badge').setAttribute('aria-label',`${count} unread in imported Apple messages`);}}
 for(const el of [document.querySelector('[data-channel="All Comms"]'),document.querySelector('.social-picker>summary')]){el?.querySelector('.notification-badge')?.remove();const total=(snapshot?.unreadTotal||0)+imported.filter(r=>r.unread).length;actualBadge(el,total);const badge=el?.querySelector('.notification-badge');if(badge){badge.title=total.toLocaleString()+' unread across the Gmail and Apple snapshots';badge.setAttribute('aria-label',badge.title);}}
 renderComms();return imported.length;
}
const appleImportBox=document.createElement('div');appleImportBox.className='apple-import-controls';appleImportBox.innerHTML='<label class="apple-import-button">Import Apple history<input type="file" accept=".json,application/json" aria-label="Import Apple Messages and call history"></label><span role="status" id="appleImportStatus">Import a Mac export. Stored in this browser only.</span>';
document.querySelector('.comms-controls').append(appleImportBox);
appleImportBox.querySelector('input').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());const n=applyAppleImport(data);document.querySelector('#appleImportStatus').textContent=`${n.toLocaleString()} records loaded. Saving in this browser…`;if(parent!==window)parent.postMessage({type:'crm-apple-save',data},'*');else document.querySelector('#appleImportStatus').textContent='Loaded for this session. Open Inbox inside the CRM to retain this import.';}catch(error){document.querySelector('#appleImportStatus').textContent=error.message;}finally{e.target.value='';}});
window.addEventListener('message',event=>{if(event.source!==parent)return;if(event.data?.type==='crm-apple-data'){try{applyAppleImport(event.data.data);document.querySelector('#appleImportStatus').textContent='Apple history restored from this browser.';}catch{document.querySelector('#appleImportStatus').textContent='Saved Apple import could not be loaded.';}}if(event.data?.type==='crm-apple-saved')document.querySelector('#appleImportStatus').textContent=event.data.ok?'Apple history saved in this browser.':'Loaded for this session; browser storage unavailable.';});
const baseCurrentMessages=currentMessages;
currentMessages=function(){return baseCurrentMessages().filter(m=>activeChannel!=='All Comms'||m.direction!=='outgoing');};
renderAllComms=function(items){$('#calendarToggle').hidden=true;if(!availableChannel(activeChannel)){$('#commsLayout').innerHTML=noChannelData();return;}const pages=Math.max(1,Math.ceil(items.length/inboxPageSize));inboxPage=Math.min(inboxPage,pages-1);const shown=items.slice(inboxPage*inboxPageSize,(inboxPage+1)*inboxPageSize);$('#commsLayout').innerHTML=`<div class="inbox-calendar-nav"><span>${items.length.toLocaleString()} records</span><button data-inbox-page="-1" ${inboxPage===0?'disabled':''}>Previous</button><span>${inboxPage+1} / ${pages}</span><button data-inbox-page="1" ${inboxPage===pages-1?'disabled':''}>Next</button></div><div class="all-list">${shown.map(m=>`<button class="all-row" data-open-person="${inboxEscape(m.id)}"><span class="all-name">${inboxEscape(m.sender)}<small class="inbox-subject">${inboxEscape(m.subject)}</small><small class="inbox-date">${inboxEscape(new Date(m.date).toLocaleString())} · ${inboxEscape(m.status)}${m.direction==='outgoing'?' · From you':''}</small></span><span class="channel-logo">${logoMarkup(m.channel)}</span><span class="all-channel">${inboxEscape(m.channel)} ${m.unread?'<span class="unread-dot" aria-label="Unread"></span>':''}</span></button>`).join('')||'<p class="p-6">No matching records.</p>'}</div>`;};
const gmailDetail=detailHTML;
detailHTML=function(m){if(m.channel==='Gmail')return gmailDetail(m);return `<article class="detail-card"><div class="detail-title"><h4>${inboxEscape(m.sender)}</h4><button class="detail-close" data-close-detail aria-label="Close message detail">×</button></div><p class="detail-copy">${inboxEscape(m.channel)} · ${inboxEscape(m.service)}<br>${inboxEscape(new Date(m.date).toLocaleString())} · ${inboxEscape(m.status)} · ${m.direction==='outgoing'?'From you':'Incoming'}</p>${m.participants.length>1?`<p class="detail-copy">Participants: ${inboxEscape(m.participants.join(', '))}</p>`:''}<h3 class="message-subject">${inboxEscape(m.subject)}</h3><p class="detail-copy">${inboxEscape(m.preview)}</p>${m.hasAttachment?'<p class="detail-copy">Attachment present in Messages; attachment files are not included in this import.</p>':''}<p class="detail-copy">Imported from your Mac. No message will be sent and no call will be placed.</p></article>`;};
renderComms=function(){if(!activeChannel)return;const connected=availableChannel(activeChannel);$('#channelKicker').textContent=connected?'Imported communications':'Not connected';$('#channelTitle').textContent=activeChannel==='All Comms'?'Inbox — who reached out':activeChannel;$('#channelDescription').textContent=activeChannel==='All Comms'?'Received Gmail, Apple messages, and incoming calls. Open each channel for sent and received history.':connected?(activeChannel==='Gmail'?'Recent Gmail Inbox snapshot.':`Mac export · ${appleSource.sources[activeChannel].imported.toLocaleString()} of ${appleSource.sources[activeChannel].available.toLocaleString()} available records · Latest ${new Date(appleSource.sources[activeChannel].latest).toLocaleDateString()}`):'No history imported for this channel.';const items=currentMessages();if(!connected||activeMode!=='calendar')renderAllComms(items);else{$('#calendarToggle').hidden=false;document.querySelectorAll('[data-calendar-view]').forEach(b=>b.classList.toggle('active',b.dataset.calendarView===calendarView));calendarView==='week'?renderWeek(items):renderMonth(items);}const m=messages.find(m=>m.id===selectedMessage);$('#detailWrap').innerHTML=m?detailHTML(m):'';bindMessageButtons();};
const previousOpenChannel=openChannel;openChannel=function(channel,tool){inboxPage=0;const latest=messages.find(m=>m.channel===channel);if(latest)inboxAnchor=new Date(latest.date);previousOpenChannel(channel,tool);};
document.addEventListener('click',e=>{const b=e.target.closest('[data-inbox-page]');if(b){inboxPage+=Number(b.dataset.inboxPage);selectedMessage=null;renderComms();}});
$('#commsSearch').addEventListener('input',()=>{inboxPage=0;renderComms();});
if(parent!==window)parent.postMessage({type:'crm-apple-ready'},'*');renderComms();
