/* A shared review queue. Checking boxes never changes the mailbox. */
let cleanupQueue={};try{cleanupQueue=JSON.parse(localStorage.getItem('crm-cleanup-v1')||'{}')}catch{}
let cleanupCategory='';
function cleanupRoot(id){const seen=new Set();while(id&&!seen.has(id)){seen.add(id);const n=(blueprintRows||[]).find(n=>n.id===canonicalSection(id));if(!n)return null;if(!n.parentId)return n.id;id=n.parentId;}return null;}
function cleanupCategories(c){if(c.members)return [...new Set(c.members.flatMap(cleanupCategories))];let ids=placements.contacts[c.id]??blueprintLinks.contactAssignments?.[c.id]??matchingSections(c.domain,blueprintLinks.links||[]);if(!ids?.length){const inferred=inferSectionForDomain(c.domain,c.company);ids=inferred?[inferred]:[];}const roots=[...new Set(ids.map(cleanupRoot).filter(Boolean))];return roots.length?roots:['unassigned'];}
window.crmCategoryMatches=c=>!cleanupCategory||cleanupCategories(c).includes(cleanupCategory);
window.crmCategoryNodeVisible=id=>!cleanupCategory||(cleanupCategory!=='unassigned'&&cleanupRoot(id)===cleanupCategory);
const originalFiltered=filtered;filtered=()=>originalFiltered().filter(crmCategoryMatches);
function cleanupTarget(c){return {key:c.members?'domain:'+c.domain:'email:'+(c.email||c.id),name:c.name,address:c.members?'@'+c.domain:c.email||c.phone||c.name,scope:c.members?'Company/domain':'Contact',category:cleanupCategories(c)};}
function saveCleanup(){try{localStorage.setItem('crm-cleanup-v1',JSON.stringify(cleanupQueue));return true;}catch{alert('Checklist could not be saved. Your mailbox was not changed.');return false;}}
function cleanupOptions(){return [{id:'',name:'All'},...(blueprintRows||[{id:'p',name:'Personal'},{id:'h',name:'Health'},{id:'w',name:'Work'},{id:'pr',name:'Projects'}]).filter(n=>!n.parentId).map(n=>({id:n.id,name:n.name.replace(/^[A-Z]\s*-\s*/, '')})),{id:'unassigned',name:'Unassigned'}];}
function sendCleanupState(){const frame=document.querySelector('.inbox-frame');if(frame)frame.contentWindow.postMessage({type:'crm-cleanup-state',category:cleanupCategory,options:cleanupOptions(),queue:cleanupQueue,contacts:contacts.map(c=>({id:c.id,name:c.name,email:c.email,domain:c.domain,categories:cleanupCategories(c)}))},'*');}
const cleanupBar=document.createElement('section');cleanupBar.className='cleanup-bar';cleanupBar.setAttribute('aria-label','Category and cleanup controls');document.querySelector('#content').before(cleanupBar);
function paintCleanupBar(){cleanupBar.innerHTML=`<details class="category-picker"><summary>Category: ${esc(cleanupOptions().find(o=>o.id===cleanupCategory)?.name||'All')} ▾</summary><div class="category-segments" role="group" aria-label="Filter by category">${cleanupOptions().map(o=>`<button data-cleanup-category="${esc(o.id)}" aria-pressed="${o.id===cleanupCategory}">${esc(o.name)}</button>`).join('')}</div></details><button class="cleanup-review">☑ Cleanup checklist <span>${Object.values(cleanupQueue).filter(x=>x.archive||x.unsubscribe).length}</span></button>`;cleanupBar.querySelectorAll('[data-cleanup-category]').forEach(b=>b.onclick=()=>{cleanupCategory=b.dataset.cleanupCategory;page=0;if(view!=='inbox')render();paintCleanupBar();sendCleanupState();});cleanupBar.querySelector('.cleanup-review').onclick=()=>showCleanup();}
function showCleanup(target){let dialog=document.querySelector('#cleanup-dialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='cleanup-dialog';document.body.append(dialog);}let pending=Object.values(cleanupQueue).filter(x=>x.archive||x.unsubscribe);if(target&&!pending.some(x=>x.key===target.key))pending.unshift({...target,archive:false,unsubscribe:false});dialog.innerHTML=`<header><h2>Cleanup checklist</h2><button data-cleanup-close aria-label="Close cleanup checklist">✕</button></header><p>Choose what to review. Nothing is archived or unsubscribed automatically. Saved in this browser.</p>${target?`<p class="cleanup-current">Selected: <strong>${esc(target.name)}</strong></p>`:''}<div class="cleanup-entries">${pending.map(x=>`<article class="cleanup-entry"><strong>${esc(x.name)}</strong><small>${esc(x.scope||'Sender')} · ${esc(x.address)}</small>${/nasa|google/i.test(x.name+' '+x.address)?'<small class="cleanup-protected">Previously requested to keep — review carefully</small>':''}<div class="cleanup-checks"><label><input type="checkbox" data-key="${esc(x.key)}" data-action="unsubscribe" ${x.unsubscribe?'checked':''}> Unsubscribe</label><label><input type="checkbox" data-key="${esc(x.key)}" data-action="archive" ${x.archive?'checked':''}> Archive</label></div></article>`).join('')||'<p>Your checklist is empty. Use the checklist icon beside a contact or company in any tab.</p>'}</div><footer><button data-export-cleanup ${pending.length?'':'disabled'}>Export checklist</button><small>Unsubscribe applies to email subscriptions; calls and personal messages can only be queued for archive review.</small></footer>`;
 dialog.querySelector('[data-cleanup-close]').onclick=()=>dialog.close();dialog.querySelectorAll('input').forEach(box=>{const row=pending.find(x=>x.key===box.dataset.key);if(row?.scope==='Apple conversation'&&box.dataset.action==='unsubscribe')box.disabled=true;box.onchange=()=>{const prior=cleanupQueue[box.dataset.key]||row;cleanupQueue[box.dataset.key]={...prior,[box.dataset.action]:box.checked,updatedAt:new Date().toISOString()};saveCleanup();paintCleanupBar();sendCleanupState();};});dialog.querySelector('[data-export-cleanup]').onclick=()=>{const blob=new Blob([JSON.stringify({format:'crm-cleanup-review-v1',exportedAt:new Date().toISOString(),actions:Object.values(cleanupQueue).filter(x=>x.archive||x.unsubscribe)},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='crm-cleanup-checklist.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};if(!dialog.open)dialog.showModal();}
function addCleanupButtons(){const entities=new Map([...contacts,...companies].map(c=>[c.id,c]));const roots=document.querySelectorAll('#content [data-open],#content [data-history-contact]');const done=new Set();for(const el of roots){const id=el.dataset.open||el.dataset.historyContact;const c=entities.get(id);if(!c)continue;if(el.matches('.account-row')&&!el.parentElement.classList.contains('cleanup-account-line')){const wrapper=document.createElement('div');wrapper.className='cleanup-account-line';el.before(wrapper);wrapper.append(el);}const host=el.closest('tr')?.lastElementChild||el.closest('.identity-card')?.querySelector('.card-action')||el.closest('[data-history-contact]')||el.parentElement;if(!host||done.has(host))continue;done.add(host);if([...host.children].some(b=>b.dataset?.cleanupFor===id))continue;const b=document.createElement('button');b.type='button';b.className='cleanup-item';b.dataset.cleanupFor=id;b.title='Cleanup checklist for '+c.name;b.setAttribute('aria-label',b.title);b.textContent='☑';b.onclick=e=>{e.stopPropagation();showCleanup(cleanupTarget(c));};host.append(b);}}
let cleanupScheduled=false;new MutationObserver(()=>{if(cleanupScheduled)return;cleanupScheduled=true;requestAnimationFrame(()=>{cleanupScheduled=false;addCleanupButtons();});}).observe(document.querySelector('#content'),{childList:true,subtree:true});
window.addEventListener('message',e=>{const frame=document.querySelector('.inbox-frame');if(!frame||e.source!==frame.contentWindow||e.origin!=='null')return;if(e.data?.type==='crm-cleanup-ready')sendCleanupState();if(e.data?.type==='crm-cleanup-open'){const t=e.data.target;if(t&&typeof t.key==='string'&&typeof t.name==='string')showCleanup({key:t.key,name:t.name,address:String(t.address||''),scope:t.scope==='Apple conversation'?'Apple conversation':'Sender'});}});
const priorRenderCleanup=render;render=function(){priorRenderCleanup();paintCleanupBar();};
window.addEventListener('storage',e=>{if(e.key==='crm-cleanup-v1'){try{cleanupQueue=JSON.parse(e.newValue||'{}');paintCleanupBar();sendCleanupState();}catch{}}});
paintCleanupBar();addCleanupButtons();
