let touchpoints=null,historyLoading=false,historyError=false,historyGroups=new Map();
const historyMonths=['January','February','March','April','May','June','July','August','September','October','November','December'];
function weekStart(date){const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-((d.getUTCDay()+6)%7));return d.toISOString().slice(0,10)}
function weekLabel(date){const d=new Date(date+'T12:00:00Z');return 'Week of '+historyMonths[d.getUTCMonth()].slice(0,3)+' '+d.getUTCDate()}
function historyDisclosure(key,title,rows,level,path){historyGroups.set(key,{rows,level,path});return `<details class="history-group" data-history-key="${esc(key)}"><summary><span>${esc(title)}</span><small>${rows.length.toLocaleString()}</small></summary><div class="history-children"></div></details>`}
function renderTouchpoints(){
 $('#pagination').innerHTML='';if(!touchpoints){$('#content').innerHTML=`<p class="empty">${historyError?'History could not load.':'Loading touchpoints…'}${historyError?'<button id="retry-history">Retry</button>':''}</p>`;if(historyError){$('#retry-history').onclick=()=>{historyError=false;renderTouchpoints()};return}if(!historyLoading){historyLoading=true;fetch('history-index.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(rows=>{touchpoints=rows;historyLoading=false;if(view==='history')render()}).catch(()=>{historyLoading=false;historyError=true;if(view==='history')render()})}return;}
 const byContact=new Map(contacts.map(c=>[c.id,c]));const tokens=search.toLowerCase().split(/\s+/).filter(Boolean);
 const rows=touchpoints.filter(r=>{const c=byContact.get(r.contactId);if(!c)return false;if(label&&!(c.labels||[c.label]).includes(label))return false;if(!tokens.length)return true;const date=new Date(r.date+'T12:00:00Z');const text=[c.name,c.company,c.email,c.domain,c.label,r.date,historyMonths[date.getUTCMonth()],date.getUTCDate(),weekLabel(weekStart(r.date)),r.subject,r.context].join(' ').toLowerCase();return tokens.every(t=>text.includes(t))});
 historyGroups=new Map();$('#result-count').textContent=rows.length.toLocaleString()+' touchpoints';
 $('#content').innerHTML=`<section class="history-panel" aria-label="History by year, month and week"><nav class="history-breadcrumb" aria-label="History location"><button id="history-all">All Touchpoints</button><span id="history-path"></span></nav><div class="history-tree">${Object.entries(groupBy(rows,r=>r.date.slice(0,4))).sort(([a],[b])=>b.localeCompare(a)).map(([year,rs])=>historyDisclosure(year,year,rs,'year',[year])).join('')||'<p class="empty">No matching touchpoints.</p>'}</div></section>`;
 $('#history-all').onclick=()=>{$('#history-path').textContent='';document.querySelectorAll('.history-group').forEach(d=>d.open=false)};
}
renderHistory=renderTouchpoints;
document.addEventListener('toggle',e=>{
 const d=e.target;if(!d.matches?.('.history-group')||!d.open)return;const g=historyGroups.get(d.dataset.historyKey);if(!g)return;$('#history-path').textContent=' / '+g.path.join(' / ');if(d.dataset.loaded)return;d.dataset.loaded='true';const body=d.querySelector(':scope > .history-children');
 if(g.level==='year'){body.innerHTML=Object.entries(groupBy(g.rows,r=>r.date.slice(0,7))).sort(([a],[b])=>b.localeCompare(a)).map(([month,rs])=>{const name=historyMonths[Number(month.slice(5))-1];return historyDisclosure(month,name,rs,'month',[...g.path,name])}).join('')}
 else if(g.level==='month'){body.innerHTML=Object.entries(groupBy(g.rows,r=>weekStart(r.date))).sort(([a],[b])=>b.localeCompare(a)).map(([week,rs])=>historyDisclosure(d.dataset.historyKey+'/'+week,weekLabel(week),rs,'week',[...g.path,weekLabel(week)])).join('')}
 else {const people=new Map(contacts.map(c=>[c.id,c]));body.innerHTML=g.rows.map(r=>{const c=people.get(r.contactId);return `<details class="history-touchpoint" data-history-contact="${esc(r.contactId)}" data-history-index="${r.index}"><summary><strong>${esc(c.name)}</strong><span>${esc(r.subject||'Touchpoint')}</span><time datetime="${esc(r.date)}">${esc(r.date)}</time></summary><div class="history-message"></div></details>`}).join('')}
},true);
const touchpointHistoryCache=new Map();
document.addEventListener('toggle',async e=>{const d=e.target;if(!d.matches?.('.history-touchpoint')||!d.open||d.dataset.loaded)return;d.dataset.loaded='true';const body=d.querySelector('.history-message'),id=d.dataset.historyContact;body.textContent='Loading saved message…';try{if(!touchpointHistoryCache.has(id))touchpointHistoryCache.set(id,fetch('history/'+encodeURIComponent(id)+'.json').then(r=>{if(!r.ok)throw Error();return r.json()}));const rows=await touchpointHistoryCache.get(id),m=rows[Number(d.dataset.historyIndex)];if(!m)throw Error();body.innerHTML=`<p class="history-source">Saved spreadsheet message · ${esc(m.email||'')}</p><p>${esc(m.snippet||'No saved snippet.')}</p>${m.context?`<p>${esc(m.context)}</p>`:''}<button data-open="${esc(id)}">Open contact profile</button>`;}catch{touchpointHistoryCache.delete(id);d.dataset.loaded='';body.textContent='Could not load. Collapse and reopen to retry.'}},true);
