/* Present a dated Gmail snapshot. No synthetic messages or reply-status claims. */
const inboxEscape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const snapshot=window.inboxSnapshot;
let inboxAnchor=new Date(snapshot?.emails?.[0]?.date||Date.now());
function isoLocal(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function safeGmailLink(url){try{const u=new URL(url);return u.protocol==='https:'&&u.hostname==='mail.google.com'?u.href:'https://mail.google.com/'}catch{return 'https://mail.google.com/'}}
messages.splice(0,messages.length,...(snapshot?.emails||[]).map(e=>{const email=(e.from.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)||[''])[0];const sender=e.from.replace(email,'').replace(/[<>]/g,'').trim()||email||'Unknown sender';return {id:e.id,channel:'Gmail',sender,email,date:e.date,dateKey:isoLocal(new Date(e.date)),subject:e.subject,preview:e.snippet,status:e.labels.includes('UNREAD')?'Unread':'Read',unread:e.labels.includes('UNREAD'),hasAttachment:e.hasAttachment,url:safeGmailLink(e.url),known:null};}));
document.querySelector('[data-template-id="comms-heading"]').textContent='INBOX';
const note=document.querySelector('.comms-note');note.textContent=snapshot?`${messages.length} recent Gmail Inbox messages · Updated ${new Date(snapshot.importedAt).toLocaleString()} · Snapshot, not continuous sync`:'Gmail data unavailable.';
currentMessages=function(){const q=$('#commsSearch').value.trim().toLowerCase();return messages.filter(m=>(activeChannel==='All Comms'||m.channel===activeChannel)&&[m.sender,m.email,m.subject,m.preview,m.dateKey,new Date(m.date).toLocaleDateString()].join(' ').toLowerCase().includes(q));};
function noChannelData(){return `<div class="no-visual"><span>${inboxEscape(activeChannel)} is not connected. No messages or calls have been imported.</span></div>`;}
renderAllComms=function(items){$('#calendarToggle').hidden=true;if(activeChannel!=='All Comms'&&activeChannel!=='Gmail'){$('#commsLayout').innerHTML=noChannelData();return}$('#commsLayout').innerHTML=`<div class="all-list">${items.map(m=>`<button class="all-row" data-open-person="${inboxEscape(m.id)}"><span class="all-name">${inboxEscape(m.sender)}<small class="inbox-subject">${inboxEscape(m.subject)}</small><small class="inbox-date">${inboxEscape(new Date(m.date).toLocaleString())} · ${m.status}</small></span><span class="channel-logo">${logoMarkup('Gmail')}</span><span class="all-channel">Gmail ${m.unread?'<span class="unread-dot" aria-label="Unread"></span>':''}</span></button>`).join('')||'<p class="p-6">No messages match this search.</p>'}</div>`;};
function calendarNavigation(){return `<div class="inbox-calendar-nav"><button data-calendar-step="-1" aria-label="Previous period">‹</button><strong>${inboxEscape(inboxAnchor.toLocaleDateString(undefined,{month:'long',year:'numeric'}))}</strong><button data-calendar-step="1" aria-label="Next period">›</button><button data-calendar-latest>Latest messages</button></div>`;}
function inboxEvent(m){return `<button class="event-card" data-message="${inboxEscape(m.id)}"><span class="event-time">${inboxEscape(new Date(m.date).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}))}</span><span class="event-person">${inboxEscape(m.sender)}</span><span class="inbox-event-subject">${inboxEscape(m.subject)}</span><span class="event-meta"><span>Gmail</span><span>${m.status}</span></span></button>`;}
renderWeek=function(items){const start=new Date(inboxAnchor);start.setHours(12,0,0,0);start.setDate(start.getDate()-(start.getDay()+6)%7);const days=Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);return d});$('#commsLayout').innerHTML=calendarNavigation()+`<div class="calendar-shell"><div class="week-grid">${days.map(d=>`<section class="day-column"><div class="day-heading"><span>${d.toLocaleDateString(undefined,{weekday:'short'})}</span><strong>${d.getDate()}</strong></div>${items.filter(m=>m.dateKey===isoLocal(d)).map(inboxEvent).join('')}</section>`).join('')}</div></div>`;};
renderMonth=function(items){const first=new Date(inboxAnchor.getFullYear(),inboxAnchor.getMonth(),1,12),last=new Date(inboxAnchor.getFullYear(),inboxAnchor.getMonth()+1,0).getDate();$('#commsLayout').innerHTML=calendarNavigation()+`<div class="calendar-shell"><div class="month-grid">${'<div class="month-cell muted-day"></div>'.repeat((first.getDay()+6)%7)}${Array.from({length:last},(_,i)=>{const d=new Date(first);d.setDate(i+1);return `<section class="month-cell"><span class="month-date">${i+1}</span>${items.filter(m=>m.dateKey===isoLocal(d)).map(inboxEvent).join('')}</section>`}).join('')}</div></div>`;};
detailHTML=function(m){return `<article class="detail-card"><div class="detail-title"><h4>${inboxEscape(m.sender)}</h4><button class="detail-close" data-close-detail aria-label="Close message detail">×</button></div><p class="detail-copy">${inboxEscape(m.email)} · ${inboxEscape(new Date(m.date).toLocaleString())} · ${m.status}</p><h3 class="message-subject">${inboxEscape(m.subject)}</h3><p class="detail-copy">${inboxEscape(m.preview)}</p>${activeMode==='visual'?`<div class="no-visual">${m.hasAttachment?'This email has an attachment. Open Gmail to view it.':'No attachment indicated for this email.'}</div>`:''}<a class="add-inline" href="${inboxEscape(m.url)}" target="_blank" rel="noopener noreferrer">Open real message in Gmail ↗</a></article>`;};
renderComms=function(){if(!activeChannel)return;const connected=activeChannel==='All Comms'||activeChannel==='Gmail';$('#channelKicker').textContent=connected?'Gmail Inbox':'Not connected';$('#channelTitle').textContent=activeChannel==='All Comms'?'All Inbox messages':activeChannel;$('#channelDescription').textContent=connected?'Recent received messages, delivered through Gmail. Read/unread status reflects the snapshot.':'Channel available in navigation; no live integration connected.';const items=currentMessages();if(!connected||activeMode!=='calendar')renderAllComms(items);else{$('#calendarToggle').hidden=false;document.querySelectorAll('[data-calendar-view]').forEach(b=>b.classList.toggle('active',b.dataset.calendarView===calendarView));calendarView==='week'?renderWeek(items):renderMonth(items)}const m=messages.find(m=>m.id===selectedMessage);$('#detailWrap').innerHTML=m?detailHTML(m):'';bindMessageButtons();};
document.addEventListener('click',e=>{const step=e.target.closest('[data-calendar-step]');if(step){calendarView==='week'?inboxAnchor.setDate(inboxAnchor.getDate()+Number(step.dataset.calendarStep)*7):inboxAnchor=new Date(inboxAnchor.getFullYear(),inboxAnchor.getMonth()+Number(step.dataset.calendarStep),1);renderComms()}if(e.target.closest('[data-calendar-latest]')){inboxAnchor=new Date(messages[0]?.date||Date.now());renderComms()}});
document.querySelectorAll('.notification-badge').forEach(b=>b.remove());
function actualBadge(el,count){if(!el||!count)return;const b=document.createElement('span');b.className='notification-badge';b.textContent=count>99?'99+':count;b.title=count.toLocaleString()+' unread in Gmail Inbox at snapshot time';b.setAttribute('aria-label',b.title);el.append(b)}
actualBadge(document.querySelector('[data-channel="All Comms"]'),snapshot?.unreadTotal);actualBadge(document.querySelector('[data-channel="Gmail"]'),snapshot?.unreadTotal);actualBadge(document.querySelector('.social-picker>summary'),snapshot?.unreadTotal);
activeChannel='All Comms';activeMode='text';selectedMessage=null;renderComms();
