// GitHub Contents API is the authenticated shared store. Credentials stay in memory.
const syncEndpoint='https://api.github.com/repos/zainkhan1994/CRM/contents/v2/network-state.json';
let syncToken='',syncBusy=false,syncTimer=null,syncMessage='Local changes — connect GitHub to sync',syncedState=null;
function updateSyncStatus(){const el=document.querySelector('#sync-status');if(el)el.textContent=syncMessage;}
function queueSync(){syncMessage=syncToken?'Saving…':'Local changes — connect GitHub to sync';updateSyncStatus();clearTimeout(syncTimer);if(syncToken)syncTimer=setTimeout(pushState,500);}
function cleanState(s){const result={contacts:{},parents:{},deleted:{}};if(!s||typeof s!=='object')return result;for(const [k,v] of Object.entries(s.contacts||{}))if(Array.isArray(v)&&v.every(x=>typeof x==='string'))result.contacts[k]=v;for(const [k,v] of Object.entries(s.parents||{}))if(typeof v==='string')result.parents[k]=v;for(const [k,v] of Object.entries(s.deleted||{}))if(typeof v==='boolean')result.deleted[k]=v;return result;}
function encodeState(s){return btoa(String.fromCharCode(...new TextEncoder().encode(JSON.stringify(s))));}
async function readShared(){const r=await fetch(syncEndpoint,{cache:'no-store',headers:{Accept:'application/vnd.github+json',...(syncToken?{Authorization:'Bearer '+syncToken}:{})}});if(r.status===404)return {sha:null,state:cleanState(null)};if(!r.ok)throw Error('GitHub access failed ('+r.status+').');const body=await r.json();const bytes=Uint8Array.from(atob(body.content.replace(/\s/g,'')),c=>c.charCodeAt(0));return {sha:body.sha,state:cleanState(JSON.parse(new TextDecoder().decode(bytes)))};}
async function pushState(){if(!syncToken||syncBusy)return;syncBusy=true;const snapshot=cleanState(placements);try{for(let attempt=0;attempt<3;attempt++){const remote=await readShared(),merged=remote.state;for(const field of ['contacts','parents','deleted'])for(const [key,value] of Object.entries(snapshot[field]))if(!syncedState||JSON.stringify(value)!==JSON.stringify(syncedState[field]?.[key]))merged[field][key]=value;const r=await fetch(syncEndpoint,{method:'PUT',headers:{Authorization:'Bearer '+syncToken,Accept:'application/vnd.github+json','Content-Type':'application/json'},body:JSON.stringify({message:'Update CRM Network placements',content:encodeState(merged),...(remote.sha?{sha:remote.sha}:{})})});if(r.status===409||r.status===422){if(attempt<2)continue;}if(!r.ok)throw Error('Save failed ('+r.status+'). Check token repository access.');const newer=JSON.stringify(placements)!==JSON.stringify(snapshot);syncedState=cleanState(merged);if(!newer){placements=merged;localStorage.setItem(placementKey,JSON.stringify(placements));}syncMessage='Synced to GitHub';updateSyncStatus();if(view==='network')render();if(newer)setTimeout(pushState,500);return;}}catch(e){syncMessage=e.message+' Local changes retained.';updateSyncStatus();}finally{syncBusy=false;}}
function connectSync(){let d=document.querySelector('#sync-dialog');if(!d){d=document.createElement('dialog');d.id='sync-dialog';document.body.append(d)}d.innerHTML='<form method="dialog"><button>Close</button></form><h2>Connect cross-device sync</h2><p>Create a GitHub fine-grained token for <b>zainkhan1994/CRM</b> only, with <b>Contents: Read and write</b>. Enter it here on each device. It stays in memory until this page closes.</p><p><a href="https://github.com/settings/personal-access-tokens/new" target="_blank" rel="noopener noreferrer">Create repository-scoped token</a></p><input type="password" autocomplete="off" aria-label="Repository-scoped GitHub token" placeholder="GitHub fine-grained token"><button id="start-sync">Connect and sync</button><p id="sync-feedback" role="status"></p>';d.querySelector('#start-sync').onclick=async()=>{const input=d.querySelector('input');syncToken=input.value.trim();input.value='';if(!syncToken)return;await pushState();d.querySelector('#sync-feedback').textContent=syncMessage;if(syncMessage==='Synced to GitHub')d.close()};d.showModal();}
async function pullState(){if(syncBusy)return;try{const remote=await readShared();const base=syncedState;const next=cleanState(remote.state);for(const field of ['contacts','parents','deleted'])for(const [k,v] of Object.entries(placements[field]||{}))if(!base||JSON.stringify(v)!==JSON.stringify(base[field]?.[k]))next[field][k]=v;const changed=JSON.stringify(placements)!==JSON.stringify(next);syncedState=cleanState(remote.state);placements=next;localStorage.setItem(placementKey,JSON.stringify(placements));if(changed&&view==='network')render();}catch{}}
pullState();setInterval(()=>{if(document.visibilityState==='visible')pullState()},30000);
